apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: nginxapp
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      name: nginxpod
      labels:
        app: nginxapp
    spec:
      containers:
      - name: mycontainer
        image: nginx:1.19.0 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nginxapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31974