apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: test-ns
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nginxapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      name: nginxpod
      labels:
        app: nginxapp
    spec:
      containers:
      - name: mycontainer
        image: nginx:1.19.0 
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nginxapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31974