apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: nginxapp
  strategy:
    type: Recreate
  template:
    metadata:
      name: nginxpod
      labels:
        app: nginxapp
    spec:
      containers:
      - name: mycontainer
        image: nginx:1.19.0 
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
    
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myhpa
  namespace: test-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mydeploy
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nginxapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31974