apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: test-ns
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do wget -q -O- http://nginxsvc:80; done']
