apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "devdb"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "devdb@123"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: ravisrma/spring-boot-mongo:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: "mongo"
        - name: MONGO_DB_DATABASE
          value: "employee-service-blog"
        - name: MONGO_DB_USERNAME
          value: "devdb"
        - name: MONGO_DB_PASSWORD
          value: "devdb@123"
        - name: MONGO_DB_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30036
  selector:
    app: spring-boot-app