apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    app: myapp
  namespace: test-ns
spec:
  containers:
  - name: mycontainer
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100
        memory: 152Mi
      limits:
        cpu: 200
        memory: 250Mi

---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
