apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: springbootscpvc
  namespace: test-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2