apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubecost-cost-analyzer
  namespace: kubecost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubecost-prometheus-server
  namespace: kubecost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
