apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      name: rspod
      labels:
        app: nginxapp
    spec:
      containers:
      - name: mycontainer
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nginxapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31974
